#!/usr/bin/env python3
"""
Send a weekly digest (or any markdown report) as a formatted HTML email with:
  - Cyvore logo inline at the top (cid:cyvore-logo)
  - Local .md hyperlinks stripped from the email body (they don't resolve in mail
    clients) but kept in the source file. http(s):// and mailto: links are preserved.
  - Live link to the Cyvore GTM Weekly Sync Google Sheet (when --week is given
    and the matching tab exists) appended to the body.
  - Auto-attached: the source markdown, a CSV export of the current week's
    Sheet tab (was xlsx pre-2026-W22 — see tools/sheets/sheets-client.py), and
    the matching output/pipeline/{YYYY-WW}/sync-log.md (if it exists).
  - Optional extra attachments via --attach.

This is the standard send path for the Chief-of-Staff exec-comms skill (audience=weekly).
The tool intentionally does NOT modify the source file — what's on disk stays canonical.

Usage:

    # Most common: send this week's digest with all defaults
    python3 tools/email/send-digest.py --week 2026-21

    # Send a specific file (any markdown), keep the auto-attachments
    python3 tools/email/send-digest.py --file output/exec-comms/board/2026-Q2.md

    # Override recipient and subject
    python3 tools/email/send-digest.py --week 2026-21 \
        --to "ori@cyvore.com,yoav@cyvore.com" \
        --subject "Weekly Digest — Week 2026-21"

    # Add extra attachments (target-accounts list, screenshots, etc.)
    python3 tools/email/send-digest.py --week 2026-21 \
        --attach output/target-accounts.md \
        --attach output/pipeline/2026-21/hubspot-hygiene-form.md

    # Skip the CSV (leaner email — Sheet link in body still works)
    python3 tools/email/send-digest.py --week 2026-21 --no-csv

Reads SMTP credentials and the default recipient from `tools/email/email-config.json`.
"""

import argparse
import importlib.util
import json
import re
import smtplib
import sys
from datetime import date, datetime, timedelta
from email.mime.application import MIMEApplication
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

try:
    import markdown
except ImportError:
    sys.stderr.write("ERROR: 'markdown' package not installed. Run: pip install markdown\n")
    sys.exit(2)

REPO = Path(__file__).resolve().parents[2]
CONFIG_PATH = REPO / "tools" / "email" / "email-config.json"
RECIPIENTS_PATH = REPO / "tools" / "email" / "team-recipients.json"
LOGO_PATH = REPO / "tools" / "assets" / "cyvore-logo-mark.png"

# Match [text](path) where path does NOT start with http://, https://, or mailto:
LOCAL_MD_LINK_PATTERN = re.compile(r"\[([^\]]+)\]\((?!https?://|mailto:)[^)]+\)")

HTML_WRAPPER = """\
<!DOCTYPE html>
<html><head><style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1a1a1a; line-height: 1.6; max-width: 820px; margin: 0 auto; padding: 20px; }}
.sheet-link {{ background: #f0f7ff; border: 1px solid #c2dcfe; border-radius: 6px; padding: 12px 16px; margin: 16px 0; }}
.sheet-link a {{ font-weight: 600; }}
h1 {{ color: #111; border-bottom: 2px solid #e0e0e0; padding-bottom: 8px; }}
h2 {{ color: #333; margin-top: 28px; }}
h3 {{ color: #555; }}
table {{ border-collapse: collapse; width: 100%; margin: 16px 0; font-size: 0.95em; }}
th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; vertical-align: top; }}
th {{ background-color: #f5f5f5; font-weight: 600; }}
tr:nth-child(even) {{ background-color: #fafafa; }}
blockquote {{ border-left: 3px solid #ccc; margin: 16px 0; padding: 8px 16px; color: #555; }}
code {{ background: #f4f4f4; padding: 2px 6px; border-radius: 3px; font-size: 0.9em; }}
hr {{ border: none; border-top: 1px solid #e0e0e0; margin: 24px 0; }}
strong {{ color: #111; }}
a {{ color: #0a66c2; text-decoration: none; }}
a:hover {{ text-decoration: underline; }}
</style></head><body>
{header_html}
{sheet_link_html}
{body}
<hr><p style="color:#999; font-size:0.85em;">Generated by Chief of Staff (exec-comms). Source markdown attached for canonical formatting.</p>
</body></html>
"""

H1_PATTERN = re.compile(r"^\s*#\s+(.+?)\s*$", re.MULTILINE)


def extract_h1(md_src):
    """Pull the first H1 out of the markdown source. Returns (title, body_md).
    The H1 is removed from body_md so it doesn't render twice (it goes inline
    next to the logo instead).
    """
    m = H1_PATTERN.search(md_src)
    if not m:
        return None, md_src
    title = m.group(1).strip()
    body = md_src[: m.start()] + md_src[m.end():]
    body = body.lstrip("\n")
    return title, body


def build_header_html(title, embed_logo):
    """Email-safe header. Uses a 1-row table (not flexbox — Gmail/Outlook strip
    many CSS rules) to put the logo and the digest title on the same line."""
    has_logo = embed_logo and LOGO_PATH.exists()
    if not has_logo and not title:
        return ""
    cells = []
    if has_logo:
        cells.append(
            '<td style="vertical-align: middle; padding-right: 16px; width: 1%;">'
            '<img src="cid:cyvore-logo" alt="Cyvore" height="48" '
            'style="height: 48px; width: auto; display: block; border: 0;">'
            '</td>'
        )
    if title:
        cells.append(
            '<td style="vertical-align: middle;">'
            f'<h1 style="margin: 0; font-size: 1.5em; color: #111; '
            f'border: none; padding: 0; line-height: 1.2;">{title}</h1>'
            '</td>'
        )
    return (
        '<table cellpadding="0" cellspacing="0" border="0" width="100%" '
        'style="border-bottom: 1px solid #e0e0e0; margin-bottom: 24px; '
        'padding-bottom: 16px;">'
        f'<tr>{"".join(cells)}</tr></table>'
    )


def _load_sheets_client_module():
    """Lazy-load tools/sheets/sheets-client.py. Returns None if Sheets isn't
    configured — callers must degrade gracefully (no Sheet link, no CSV)."""
    try:
        spec = importlib.util.spec_from_file_location(
            "sheets_client", REPO / "tools" / "sheets" / "sheets-client.py"
        )
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        return mod
    except Exception as e:
        sys.stderr.write(f"WARNING: sheets-client.py failed to load: {e}\n")
        return None


def _resolve_sheets_client():
    """Best-effort SheetsClient instantiation. Returns None if not configured
    (no Sheet link in body, no CSV attached — but the email still sends)."""
    sheets_module = _load_sheets_client_module()
    if sheets_module is None:
        return None
    try:
        return sheets_module.SheetsClient()
    except SystemExit:
        # SheetsClient calls sys.exit on missing config / creds; we want a
        # softer degrade here so the email still goes through.
        sys.stderr.write(
            "WARNING: Google Sheets not configured (tools/sheets/google-sheets-config.json + "
            "credentials). Email will be sent without Sheet link or CSV.\n"
        )
        return None
    except Exception as e:
        sys.stderr.write(f"WARNING: could not connect to Google Sheets: {e}\n")
        return None


def _monday_of_iso_week(week_str):
    """'YYYY-WW' -> the date of that ISO week's Monday."""
    try:
        y, w = week_str.split("-")
        return date.fromisocalendar(int(y), int(w), 1)
    except Exception:
        return None


def resolve_tab_for_week(sc, week_str):
    """Find the Sheet tab that corresponds to the ISO week. Returns the tab
    name or None. Tab names are DD.MM.YYYY (this Monday's date)."""
    if sc is None or not week_str:
        return None
    monday = _monday_of_iso_week(week_str)
    if monday is None:
        return None
    expected = monday.strftime("%d.%m.%Y")
    if sc.tab_exists(expected):
        return expected
    # Fallback: linear scan for any DD.MM.YYYY tab whose ISO week matches.
    pattern = re.compile(r"^\s*(\d{1,2})\.(\d{1,2})\.(\d{4})\s*$")
    for name in sc.list_tabs():
        m = pattern.match(name)
        if not m:
            continue
        d, mo, y = (int(x) for x in m.groups())
        try:
            tab_date = date(y, mo, d)
        except ValueError:
            continue
        iso_y, iso_w, _ = tab_date.isocalendar()
        if f"{iso_y:04d}-{int(iso_w):02d}" == week_str:
            return name
    return None


def die(msg, code=2):
    sys.stderr.write(f"ERROR: {msg}\n")
    sys.exit(code)


def load_config():
    if not CONFIG_PATH.exists():
        die(f"Missing {CONFIG_PATH.relative_to(REPO)}. See agents/chief-of-staff/skills/exec-comms.md.")
    cfg = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    for k in ("smtp_host", "smtp_port", "sender_email", "app_password"):
        if not cfg.get(k):
            die(f"{CONFIG_PATH} missing required key {k!r}")
    return cfg


def load_audience(name):
    """Resolve an --audience preset from tools/email/team-recipients.json.
    Returns (to_list, cc_list). Dies with a helpful message if the preset
    is missing — keeps the team list out of the script and out of muscle
    memory."""
    if not RECIPIENTS_PATH.exists():
        die(f"--audience {name!r} requires {RECIPIENTS_PATH.relative_to(REPO)} to exist.")
    data = json.loads(RECIPIENTS_PATH.read_text(encoding="utf-8"))
    audiences = (data or {}).get("audiences") or {}
    if name not in audiences:
        available = ", ".join(sorted(audiences.keys())) or "(none configured)"
        die(f"Unknown --audience {name!r}. Available: {available}")
    entry = audiences[name] or {}
    to = list(entry.get("to") or [])
    cc = list(entry.get("cc") or [])
    return to, cc


def resolve_digest(args):
    if args.file:
        p = Path(args.file)
        if not p.is_absolute():
            p = REPO / p
        if not p.exists():
            die(f"--file not found: {p}")
        return p
    if not args.week:
        die("Provide either --week YYYY-WW or --file PATH.")
    p = REPO / "output" / "exec-comms" / "weekly" / f"{args.week}.md"
    if not p.exists():
        die(f"Digest not found at {p.relative_to(REPO)}. Run the exec-comms skill first.")
    return p


def auto_attach_paths(args, digest_path, sheets_client, tab_name):
    """Resolve the list of files to attach. The CSV export of this week's
    Sheet tab is generated to /tmp on the fly (was state/weekly-customer-sync.xlsx
    pre-2026-W22)."""
    paths = [digest_path]

    if not args.no_csv and sheets_client is not None and tab_name:
        csv_path = Path(f"/tmp/weekly-customer-sync-{args.week or 'current'}.csv")
        try:
            sheets_client.export_tab_csv(tab_name, csv_path)
            paths.append(csv_path)
        except Exception as e:
            sys.stderr.write(f"WARNING: CSV export of tab {tab_name!r} failed: {e}\n")

    if args.week:
        sync_log = REPO / "output" / "pipeline" / args.week / "sync-log.md"
        if sync_log.exists():
            paths.append(sync_log)

    for extra in args.attach or []:
        p = Path(extra)
        if not p.is_absolute():
            p = REPO / p
        if not p.exists():
            sys.stderr.write(f"WARNING: extra attachment not found, skipping: {p}\n")
            continue
        paths.append(p)

    seen, out = set(), []
    for p in paths:
        if p.resolve() in seen:
            continue
        seen.add(p.resolve())
        out.append(p)
    return out


def build_sheet_link_html(sheets_client, tab_name):
    """Render a small banner above the body pointing at the live Sheet tab.
    Returns '' when Sheets isn't configured or the tab doesn't exist."""
    if sheets_client is None or not tab_name:
        return ""
    try:
        url = sheets_client.tab_url(tab_name)
    except Exception:
        return ""
    return (
        '<div class="sheet-link">'
        f'Live sync sheet \u2014 tab <strong>{tab_name}</strong> in '
        f'<a href="{url}">Cyvore GTM Weekly Sync</a>. '
        "Open in browser or on phone to see / edit the source rows."
        "</div>"
    )


def build_message(cfg, to_addrs, cc_addrs, subject, digest_path, attachments, embed_logo,
                  sheet_link_html=""):
    md_src = digest_path.read_text(encoding="utf-8")
    n_stripped = len(LOCAL_MD_LINK_PATTERN.findall(md_src))
    md_for_email = LOCAL_MD_LINK_PATTERN.sub(r"\1", md_src)
    title, md_for_email = extract_h1(md_for_email)
    header_html = build_header_html(title, embed_logo)
    html_body = markdown.markdown(md_for_email, extensions=["tables", "fenced_code", "nl2br"])
    html = HTML_WRAPPER.format(
        body=html_body,
        sheet_link_html=sheet_link_html,
        header_html=header_html,
    )

    msg = MIMEMultipart("mixed")
    msg["From"] = cfg["sender_email"]
    msg["To"] = ", ".join(to_addrs)
    if cc_addrs:
        msg["Cc"] = ", ".join(cc_addrs)
    msg["Subject"] = subject

    related = MIMEMultipart("related")
    related.attach(MIMEText(html, "html"))
    if embed_logo and LOGO_PATH.exists():
        with open(LOGO_PATH, "rb") as f:
            logo = MIMEImage(f.read(), _subtype="png")
        logo.add_header("Content-ID", "<cyvore-logo>")
        logo.add_header("Content-Disposition", "inline", filename=LOGO_PATH.name)
        related.attach(logo)
    msg.attach(related)

    for path in attachments:
        suffix = path.suffix.lower()
        subtype = {
            ".xlsx": "vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            ".csv": "csv",
            ".pdf": "pdf",
        }.get(suffix, "octet-stream")
        att = MIMEApplication(path.read_bytes(), _subtype=subtype, Name=path.name)
        att["Content-Disposition"] = f'attachment; filename="{path.name}"'
        msg.attach(att)

    return msg, n_stripped


def send(cfg, msg, recipients):
    port = cfg["smtp_port"]
    pw = cfg["app_password"].replace(" ", "")
    if port == 465:
        with smtplib.SMTP_SSL(cfg["smtp_host"], port) as s:
            s.login(cfg["sender_email"], pw)
            s.sendmail(cfg["sender_email"], recipients, msg.as_string())
    else:
        with smtplib.SMTP(cfg["smtp_host"], port) as s:
            s.ehlo(); s.starttls(); s.ehlo()
            s.login(cfg["sender_email"], pw)
            s.sendmail(cfg["sender_email"], recipients, msg.as_string())


def main():
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument("--week", help="ISO week, e.g. 2026-21. Picks output/exec-comms/weekly/{week}.md and auto-attaches the matching sync log if it exists.")
    p.add_argument("--file", help="Path to a markdown file to send (overrides --week resolution).")
    p.add_argument("--audience", help="Preset audience key in tools/email/team-recipients.json (e.g. weekly-leadership). Resolves --to and --cc unless they are passed explicitly.")
    p.add_argument("--to", help="Recipient(s), comma-separated. Overrides --audience to-list. Defaults to email-config.json default_recipient when neither is set.")
    p.add_argument("--cc", default=None, help="CC recipients, comma-separated. Overrides --audience cc-list. Empty by default.")
    p.add_argument("--subject", help="Subject line. Defaults to the digest's H1 / 'Weekly Digest — {week}'.")
    p.add_argument("--attach", action="append", help="Extra files to attach. May be passed multiple times.")
    p.add_argument("--no-csv", action="store_true",
                   help="Don't generate / attach a CSV export of the current week's Sheet tab.")
    # Hidden alias for muscle memory from the xlsx era — same semantics as --no-csv.
    p.add_argument("--no-xlsx", dest="no_csv", action="store_true", help=argparse.SUPPRESS)
    p.add_argument("--no-logo", action="store_true", help="Don't embed the Cyvore logo header.")
    p.add_argument("--no-sheet-link", action="store_true",
                   help="Don't render the 'Live sync sheet' banner at the top of the email body.")
    p.add_argument("--dry-run", action="store_true", help="Build the message but don't send.")
    args = p.parse_args()

    cfg = load_config()
    digest_path = resolve_digest(args)

    audience_to, audience_cc = ([], [])
    if args.audience:
        audience_to, audience_cc = load_audience(args.audience)

    if args.to:
        to_addrs = [x.strip() for x in args.to.split(",") if x.strip()]
    elif audience_to:
        to_addrs = list(audience_to)
    else:
        default = cfg.get("default_recipient")
        if not default:
            die("No --to / --audience and no default_recipient in email-config.json.")
        to_addrs = [default]

    if args.cc is not None:
        cc_addrs = [x.strip() for x in args.cc.split(",") if x.strip()]
    else:
        cc_addrs = list(audience_cc)

    recipients = to_addrs + cc_addrs

    if not args.subject:
        text = digest_path.read_text(encoding="utf-8")
        m = re.match(r"^#\s+(.+?)\s*$", text.split("\n", 1)[0])
        title = m.group(1) if m else (f"Weekly Digest — Week {args.week}" if args.week else digest_path.stem)
        args.subject = title

    sheets_client = None
    tab_name = None
    if not (args.no_csv and args.no_sheet_link):
        sheets_client = _resolve_sheets_client()
        if sheets_client is not None and args.week:
            tab_name = resolve_tab_for_week(sheets_client, args.week)

    sheet_link_html = ""
    if not args.no_sheet_link:
        sheet_link_html = build_sheet_link_html(sheets_client, tab_name)

    attachments = auto_attach_paths(args, digest_path, sheets_client, tab_name)

    msg, n_stripped = build_message(
        cfg, to_addrs, cc_addrs, args.subject, digest_path, attachments,
        embed_logo=not args.no_logo,
        sheet_link_html=sheet_link_html,
    )

    if args.dry_run:
        print(f"DRY RUN. Would send to: {', '.join(to_addrs)}")
        print(f"  CC: {', '.join(cc_addrs) if cc_addrs else '(none)'}")
        print(f"  Subject: {args.subject}")
        print(f"  Body: {digest_path.relative_to(REPO)}")
        print(f"  Attachments: {[a.name for a in attachments]}")
        print(f"  Inline logo: {'cyvore-logo-mark.png' if (not args.no_logo and LOGO_PATH.exists()) else '(skipped)'}")
        print(f"  Sheet link banner: {'yes (' + tab_name + ')' if sheet_link_html else 'no'}")
        print(f"  Stripped local-md links from body: {n_stripped}")
        return

    send(cfg, msg, recipients)
    print(f"Sent to: {', '.join(to_addrs)}")
    if cc_addrs:
        print(f"CC: {', '.join(cc_addrs)}")
    print(f"Subject: {args.subject}")
    print(f"Body: {digest_path.relative_to(REPO)}")
    print(f"Attachments: {', '.join(a.name for a in attachments)}")
    if not args.no_logo and LOGO_PATH.exists():
        print("Inline logo: cyvore-logo-mark.png")
    if sheet_link_html:
        print(f"Sheet link banner: tab {tab_name}")
    print(f"Stripped local-md links from body: {n_stripped}")


if __name__ == "__main__":
    main()
